package:
  name: openmmtools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm >=7.2
    - lxml

  run:
    - python
    - numpy
    - scipy
    - six
    - openmm >=7.2
    - parmed
    - mdtraj
    - netcdf4
    - pyyaml
    - lxml


test:
  requires:
    - nose
    - pymbar
# Until the NetCDF issues are resolved, actual test runs are subject to run_test.[bat,sh] (9/16/2018)
#  imports:
#    - openmmtools

about:
  home: https://github.com/choderalab/openmmtools
  license: MIT License
