package:
  name: openmmtools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - nose
    - setuptools
    - openmm
    - parmed

  run:
    - python
    - scipy
    - openmm
    - nose
    - setuptools
    - six
    - parmed


test:
  requires:
    - nose
  imports:
    - openmmtools

about:
  home: https://github.com/choderalab/openmmtools
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
